### ISSUE TITLE
discussions

### ISSUE THREAD

**Issue by sergiuprt** [roata/roataway-telegram-bot#4]
we a need a slack/discord/telegram channel for discussions, twitter is not the most suitable

**Comment by roata** [comment]
The issue tracker on Github is not enough? It is important to:

- avoid fragmentation of context across multiple locations;
- make it easy for others to follow the discussion, without having to sign up anywhere


I like the idea of Telegram, but the discussions will only be accessible to those who actually have Telegram, thus locking out some potential contributors. Those discussions will also not show in the the results of search engines - which is a downside.

Github can be easily read by anyone.

**Comment by roata** [comment]
After some time passed by, I can see that Github is not enough - only people who have a software engineering mindset actually use it.

Over the course of several months, the bot's feedback feature was triggered quite often and people used it to request new routes or just share their words of encouragement (it is a shame that only I can see the logs). 

It is obvious that a discussion platform that allows the common non-expert user voice their opinion is a must-have, otherwise this project may stagnate.

So, ladies and gentlemen (@sergiuprt, @PlugaruT, @iamandrewluca, @ralienpp), what options do you think would be worth trying?




Here are my thoughts on this matter so far:

- it should provide archives that can be read and searched by the public
- it should be open to to a wide audience
- it should not require registering an account to provide read access
- it should not be tied to a particular platform (e.g. Telegram) because the bot itself is just one part of Roataway, and hopefully the web-page tracker that Andrew works on will take off one day, and attract developers with JS/React skills that have not used Telegram.


What I tried so far:

- Twitter - not so effective
- Facebook - my account was disabled without any explanations (I assume it was reported by someone as a "non human account" or something like that)
- I registered on https://roataway.zulipchat.com/ and got a "free for open source software" package. They promised they'd roll out the "archives readable by the public" feature next week. You can already go ahead and give it a try :-)


What would be the best course of action, in your collective opinion?

**Comment by sergiuprt** [comment]
isn't slack accesible with just a link?
