### ISSUE TITLE
Extract contribution guides into CONTRIBUTING.md

### ISSUE THREAD

**Issue by unrevised6419** [roata/roataway-telegram-bot#8]
Would be better to move all instructions how to setup project and contribution to a separate file `CONTRIBUTING.md`. PR on me if green light on this.

**Comment by roata** [comment]
I would prefer to leave it as is, because it is not a long document, and it does not yet suffer from readability issues that would be resolved by breaking it down into pieces. But most important - it is short, and whoever reads it can feel confident that they've seen all there is to see.

However, if you take it upon yourself to do this, then:

- keep in mind that the the current readme is in `rst`;
- the current doc should contain a link to the newly minted section (so the reader can "flow" from one doc to the next, without having to explicitly look for it);
- add other sections that are necessary (e.g., the data structures and the format of CSV files, the code of conduct - these are candidates for another section);
- think of what sections will be needed in the future.
